
POST http://localhost:3003/user
Content-Type: application/json

{
	"name": "Astro Dev",
	"nickname": "astrodev",
	"email": "astro@dev.com"
}

###

GET http://localhost:3003/user/002



###


PUT http://localhost:3003/user/edit/002
Content-Type: application/json

{
	"name": "Astro Dev",
	"nickname": "astrodev"
}


###
POST http://localhost:3003/task
Content-Type: application/json

{
	"title": "Criar banco dos alunos",
	"description": "Devemos criar o banco dos alunos para o módulo do backend",
	"limitDate": "04/05/2020",
	"creatorUserId": "001"
}



###
POST http://localhost:3003/task

{
	"title": "Criar banco dos alunos",
	"description": "Devemos criar o banco dos alunos para o módulo do backend",
	"limitDate": "04/05/2020",
	"creatorUserId": "001"
}