
POST http://localhost:3003/user
Content-Type: application/json

{
	"name": "Astro Dev",
	"nickname": "astrodev",
	"email": "astro@dev.com"
}

###

GET http://localhost:3003/user/002



###


PUT http://localhost:3003/user/edit/1627064082737
Content-Type: application/json

{
	"name": "Astro",
	"nickname": "Astro"
}


###

POST http://localhost:3003/task
Content-Type: application/json

{
	"title": "Criar banco dos alunos",
	"description": "Devemos criar o banco dos alunos para o módulo do backend",
	"limitDate": "04/05/2022",
	"status": "done",
	"creatorUserId": "001"
}



###

GET http://localhost:3003/task/003

