let filme = prompt("Olá qual o seu fime favorito?")
let altura = prompt("Qual a sua altura?")
let cor = prompt("Qual a sua cor para o dia de hoje?")
let pais = prompt("Qual país gostaria de conhecer?")
let signo = prompt("Qual o seu signo?")

console.log("Qual seu filme favorito? ")
console.log("Resposta: ") + filme)
console.log("Qual a sua altura? " )
console.log("Resposta: ") + altura)
console.log("Qual sua cor do dia de hoje? ")
console.log("Resposta: ") + cor)
console.log("Qual país gostaria de conhecer? ")
console.log("Resposta: ") + pais )
console.log("Qual seu signo? ")
console.log("Resposta: ") + signo)

